import Link from "next/link";
export const metadata = { title: "About Yusuf" };
export default function AboutPage() {
  return <article className="personal-about"><header className="about-cover"><img src="/media/profile/yusuf-portrait.jpg" alt="Portrait of Yusuf Adekola" width={794} height={758} loading="eager"/><div><p className="eyebrow">Who am I?</p><h1>Yusuf<br/>Adekola.</h1><p className="about-cover-lead">Curious about how things work.<br/>Driven by what they can do for people.</p><p>I’m a final-year MEng Robotics and Artificial Intelligence student at University College London, based at UCL East. I’m also an Aspire Award Scholar through UCL Computer Science, in partnership with the Windsor Fellowship.</p></div></header>
    <section id="interests" className="about-interests"><p className="eyebrow">What draws me in</p><h2>From an idea<br/>to something useful.</h2><p>I’m interested in robotics, mechatronics, mechanics and design. I enjoy the point where an idea becomes something physical: working through a mechanism, shaping it in CAD, making a prototype and learning from how it behaves.</p><p>I aspire to build practical products that improve independence and everyday life. Whether the system is physical or digital, I want its purpose to guide the design, and I value working closely with the people it is meant to serve.</p></section>
    <section className="about-values"><div><p className="eyebrow">How I work</p><h2>Hands-on.<br/>Open-minded.<br/>Together.</h2></div><div><p>I enjoy taking responsibility and leading a project, but I also know that a good result comes from collaboration. I like listening to different perspectives, communicating decisions clearly and working across disciplines to turn a shared idea into a practical result.</p><p>At UCL, I share that interest through teaching, mentoring and outreach. As an ambassador for UCL East and UCL Computer Science, I enjoy helping people discover engineering and feel part of the community.</p></div></section>
    <section className="about-next"><h2>See what I’ve been making.</h2><Link href="/projects">Explore my projects ↗</Link><Link href="/contact">Get in touch ↗</Link></section>
  </article>;
}
