"use client";
import { useRef } from "react";
import Link from "next/link";
import { BuildCarousel, type BuildFrame } from "./build-carousel";
import { useScrollReveals } from "./use-scroll-reveals";
import { ibmMedia } from "@/content/ibm-media";
function frame(key:keyof typeof ibmMedia,title:string,caption:string,context:string,alt:string):BuildFrame {
 return {media:{kind:"image",...ibmMedia[key],alt},title,caption,context};
}
const processFrames=[
 frame("feature-ideation","Start with the supporter.","Personas, pain points and feature ideas brought into one shared board.","We began with the FA brief and the people using the official England app. This ideation board brings together different fan personas, their pain points and user needs, then possible features: clearer match information, faster catch-up, richer context and a more engaging second-screen experience. Alongside each idea, we asked which parts of our consulting work an assistant or agent could support.","FA feature-ideation board showing fan personas, pain points, user needs and proposed features"),
 frame("pdlc-map","Map the work behind the feature.","A shared map of discovery, delivery and launch, with human review in the loop.","Our Mural map broke the Product Development Lifecycle into research, requirements, design, development, testing and deployment. We mapped opportunities for agent assistance against that process, rather than treating AI as a shortcut around it. The board includes proposed activities and review gates; it records our thinking about the full lifecycle, not a claim that every activity on it was implemented.","Product Development Lifecycle map linking consulting stages, agent opportunities and human review gates"),
];
const workspaceFrames=[frame("playmaker-workspace","From brief to a winning play.","The client-engagement workspace that brings the workflow together.","Playmaker takes a client brief as the starting point for the engagement. Agents draft artifacts across the lifecycle, with review and approval before work becomes an input to the next stage. This screenshot shows the workspace interface; the wider process map includes both built and proposed activities.","Playmaker workspace showing the client-brief input and Run agent button")];
const originalFrames=[
 frame("original-match-report","The existing match report.","An article-led view of the match, before our prototype.","This is a reference screenshot of the existing England app. The match report begins with a large editorial photograph and leads into written coverage. We used the current app experience as one input when exploring how supporters could find key information and understand a match more quickly.","Original England app match report showing Bukayo Saka being embraced"),
 frame("original-report-detail","The detail was there to read.","Written match detail, line-ups and substitutions.","The original app supplied detailed written reporting. Our research and ideation considered how that information could be complemented by more scannable summaries and visual match context. This screenshot and the prototype screens use different fixtures; the comparison is about information structure, not a before-and-after result for one match.","Original England app screen with detailed match-report text, player names and substitutions"),
];
const prototypeFrames=[
 frame("prototype-fixtures","A clearer match starting point.","Fixtures and results brought into a concise match hub.","The team created this proof-of-concept screen using Playmaker with human intervention and review. It explores a clear route into fixtures, results and match information. The prototype was a demonstration of our product-development approach, rather than a replacement released into the official app.","Team prototype of the England app fixtures and results screen"),
 frame("prototype-match-insights","Catch up without reading everything.","Short match insights alongside the timeline.","This prototype brings concise insights and a timeline together, responding to the idea that supporters should be able to catch up quickly. Playmaker supported the drafting and development process; the team shaped and reviewed the output. The match content shown belongs to the demonstration, not a verified live-data service.","Team prototype match timeline with concise match-insight bullet points"),
 frame("prototype-lineups","See the team on the pitch.","A formation view makes player positions easier to scan.","The line-up screen explores how a pitch-based formation can communicate the team at a glance. It sits within the team's wider England app proof of concept, built through agent-assisted work and human refinement.","Team prototype showing a football line-up arranged on a pitch"),
 frame("prototype-match-stats","Give the numbers a shape.","Momentum and headline statistics in one visual view.","The statistics screen combines a momentum-style chart with headline comparison bars. It illustrates our approach to turning match information into a more visual second-screen experience. The screenshot demonstrates an interface concept; it does not establish a deployed analytics pipeline or measured improvement in fan engagement.","Team prototype showing match momentum and comparative football statistics"),
 frame("prototype-players","Make room for the people.","A player directory grouped by position.","The player screen rounds out the demonstration with a browsable directory. It shows how the team applied the approach beyond a single match panel, using Playmaker alongside human design decisions and intervention to create a connected proof of concept.","Team prototype player directory with player portraits grouped by position"),
];
const showcaseFrames=[
 frame("showcase","Bringing the story to the room.","The team presenting the FA demonstration and Playmaker at the showcase.","At the internship showcase, we presented both the England app proof of concept and the repeatable consulting approach behind it. This photograph shows the team at the FA and IBM presentation. My work spanned data and insights, business analysis, technical solutions and product design within our five-person team.","Yusuf and the internship team presenting beside a large FA and IBM display at the showcase"),
 frame("intern-team","Five different perspectives.","Our intern team at IBM.","I worked alongside Benjamin Segall, Valerie Fiamavle, Vidhisha Chadda and Ahmad R. Our different strengths helped us work across research, prioritisation, design, development and testing, and bring the toolkit and demonstration together.","The five-person IBM summer internship team standing together at IBM"),
 frame("team-and-mentors","The people behind the progress.","The wider team and the support around the internship.","Fred Baker challenged us to explore how agentic AI could enhance established consulting processes in sport and entertainment. Ben Gilpin, Georgia Smith and Jessica Harding provided guidance and feedback, with support from my manager Louise Keevill. This group photograph records the people around the project; individual roles are credited in the story rather than inferred from positions in the image.","Group photograph of Yusuf with colleagues from the internship project"),
];
const touchpoints=[
 ["Discovery","Market analysis and benchmarking","Understand the landscape."],
 ["Discovery","Current app experience","Understand what is already there."],
 ["Discovery","Personas","Understand who we are designing for."],
 ["Discovery","Requirements","Turn insight into a clear brief."],
 ["Delivery","User stories and journeys","Describe the experience we want."],
 ["Delivery","Design and architecture","Give the solution a structure."],
 ["Delivery","Acceptance criteria","Define what good looks like."],
 ["Delivery","Feature development","Bring the selected idea to life."],
];
export function IBMExperienceStory() {
 const study=useRef<HTMLElement>(null);useScrollReveals(study);
 return <article className="ibm-story project-story-study" ref={study}>
  <header className="ibm-story-hero"><div className="hex-intro"><p className="eyebrow hex-enter">IBM Consulting / Summer internship / June–September 2026</p><h1><span className="hex-title">A brief.<br/>A team.<br/>A winning play.</span></h1><p className="ibm-role">Data &amp; Insights Consultant Intern</p><p className="hex-summary hex-enter">Twelve weeks exploring how agentic AI could help consultants turn a client challenge into a useful digital experience.</p><p className="ibm-cv-note">My most recent work experience. For my full experience and CV, <Link href="/contact">get in touch ↗</Link>.</p></div><figure className="hex-hero-image"><img src={ibmMedia.presentation.src} alt="Yusuf and the team presenting beside the FA × IBM display" width={ibmMedia.presentation.width} height={ibmMedia.presentation.height} loading="eager"/></figure></header>
  <section className="hex-section" aria-labelledby="ibm-brief"><div className="hex-section-inner hex-story-grid"><div data-reveal><p className="eyebrow">01 / The people and the brief</p><h2 id="ibm-brief">Sport brings people together.<br/>So should its digital experiences.</h2><p className="hex-section-lead">I joined IBM Consulting’s Communications team, working in its sport and entertainment space, from 29 June to 18 September 2026. Our five-person intern team worked across business, technology and design on a challenge involving the official England Football App.</p></div><div className="ibm-story-card" data-reveal style={{transitionDelay:"180ms"}}><h3>My role in the team.</h3><p>As a Data &amp; Insights Consultant Intern, I contributed across research, business analysis, technical solutions and product design. That meant connecting evidence about the client and its users with the features we explored, and helping structure a workflow that could be reused.</p><p>IBM’s existing sports work, including Ferrari, Wimbledon and the US Open, gave the challenge its wider context. Fred Baker asked us to explore how agentic AI could enhance established ways of working while preserving consultant expertise, quality and human oversight.</p></div></div></section>
  <section className="hex-section ibm-warm-section" aria-labelledby="ibm-start"><div className="hex-section-inner" data-reveal><p className="eyebrow">02 / Two problems to solve</p><h2 id="ibm-start">A better feature.<br/>A better way to get there.</h2><p className="hex-section-lead">We started by brainstorming opportunities for the app: what did different supporters need, where did the current experience create friction, and which ideas were worth pursuing? At the same time, we asked how agents and assistants could support the work we were doing to answer those questions.</p><div className="ibm-question-grid"><div><span>01</span><h3>Could we use an agentic approach to address a real FA digital challenge, while keeping IBM quality?</h3></div><div><span>02</span><h3>Could the same approach become useful across other sport and entertainment clients?</h3></div></div></div></section>
  <section className="hex-section ibm-process-gallery" aria-labelledby="ibm-process"><div className="hex-section-inner hex-build-introduction" data-reveal><p className="eyebrow">03 / Understanding the work</p><h2 id="ibm-process">Reel it back in.<br/>Map the whole journey.</h2><p className="hex-section-lead">The Product Development Lifecycle takes an idea through research, requirements, design, development and testing towards launch. After a pivot, we had only a couple of weeks to produce a working proof of concept. We needed to identify concrete places for AI support, rather than try to accelerate everything at once.</p></div><div className="hex-section-inner ibm-board-grid">{processFrames.map((item,i)=><figure key={item.media.src} data-reveal><a className="ibm-board-preview" href={i===0?"/media/ibm/feature-ideation.pdf":"/media/ibm/pdlc-map.pdf"} target="_blank" rel="noopener noreferrer" aria-label={`Open full PDF: ${item.title}`}><img src={item.media.src} alt={item.media.alt} width={item.media.width} height={item.media.height} loading="lazy"/></a><figcaption><h3>{item.title}</h3><p>{item.caption}</p><a href={i===0?"/media/ibm/feature-ideation.pdf":"/media/ibm/pdlc-map.pdf"} target="_blank" rel="noopener noreferrer">Open full PDF ↗</a></figcaption></figure>)}</div><div className="hex-section-inner ibm-touchpoints" data-reveal><h3>Eight touchpoints for AI in the loop.</h3><div className="ibm-touchpoint-grid">{touchpoints.map(([phase,title,caption],i)=><div key={title}><p className="eyebrow">{phase} / 0{i+1}</p><h4>{title}</h4><p>{caption}</p></div>)}</div></div></section>
  <section className="hex-section ibm-playmaker-section" aria-labelledby="ibm-playmaker"><div className="hex-section-inner"><div className="ibm-playmaker-intro" data-reveal><p className="eyebrow">04 / The toolkit</p><img className="ibm-playmaker-logo" src="/media/ibm/playmaker-logo.svg" alt="Blue Playmaker sports-and-code logo" width={215} height={215}/><h2 id="ibm-playmaker">Playmaker.</h2><p className="hex-section-lead">An Agentic Product Development Toolkit for Sport &amp; Entertainment.</p></div><div className="hex-story-grid"><div data-reveal><h3>From client brief to reviewed work.</h3><p className="hex-section-lead">Playmaker is a client-engagement workspace built around the lifecycle we mapped. A brief starts the project; agents draft artifacts such as research, personas, requirements, user stories, design concepts and code; a person reviews them before approved work is passed to the next stage.</p></div><div className="ibm-story-card" data-reveal style={{transitionDelay:"180ms"}}><h3>Keep the consultant in the loop.</h3><p>The toolkit combines AI agents, automation and human review. Work can be approved or sent back for changes, making the consultant’s judgement part of the process rather than something added at the end.</p><p>We packaged our ways of working into a repeatable asset, alongside applying them to a football app proof of concept. The aim was faster delivery with quality preserved; we did not establish a quantified speed improvement.</p></div></div><ol className="ibm-review-loop" data-reveal><li><span>01</span><h3>Brief</h3><p>Start with the client problem.</p></li><li><span>02</span><h3>Draft</h3><p>Let an agent prepare the artifact.</p></li><li><span>03</span><h3>Review</h3><p>Approve it or request changes.</p></li><li><span>04</span><h3>Build on it</h3><p>Use approved work downstream.</p></li></ol><div className="ibm-workspace-gallery" data-reveal><div className="ibm-browser-chrome"><span aria-hidden="true">● ● ●</span><span>Playmaker / Our client-engagement web app</span></div><BuildCarousel frames={workspaceFrames} label="Playmaker workspace preview"/></div></div></section>
  <section className="hex-section ibm-phone-gallery ibm-original-gallery" aria-labelledby="ibm-before"><div className="hex-section-inner hex-build-introduction" data-reveal><p className="eyebrow">05 / The starting experience</p><h2 id="ibm-before">The app we began with.</h2><p className="hex-section-lead">The existing app provided editorial coverage and detailed written reports. Our ideation explored how to complement that with match information supporters could scan and understand more quickly.</p></div><BuildCarousel frames={originalFrames} label="Original England app reference screens" pair/></section>
  <section className="hex-section ibm-phone-gallery ibm-prototype-gallery" aria-labelledby="ibm-after"><div className="hex-section-inner hex-build-introduction" data-reveal><p className="eyebrow">06 / What we created</p><h2 id="ibm-after">A more visual matchday.</h2><p className="hex-section-lead">These five screens are from our team’s England app proof of concept, created using Playmaker with human intervention and refinement. Fixtures, concise insights, line-ups, visual statistics and player browsing demonstrate the approach in practice.</p></div><BuildCarousel frames={prototypeFrames} label="Team England app prototype screens"/></section>
  <section className="hex-section ibm-showcase-section" aria-labelledby="ibm-showcase"><div className="hex-section-inner hex-build-introduction" data-reveal><p className="eyebrow">07 / Bringing it together</p><h2 id="ibm-showcase">Show the product.<br/>Explain the process.</h2><p className="hex-section-lead">We finished with an interactive app proof of concept, a reusable toolkit and a showcase of the thinking behind both. For me, it was an opportunity to work as a consultant across the full journey, keeping the user’s needs, the client’s challenge and the wider team connected.</p></div><BuildCarousel frames={showcaseFrames} label="IBM internship showcase and team"/><div className="hex-section-inner ibm-credits" data-reveal><h3>A team effort.</h3><p>Built with Benjamin Segall, Valerie Fiamavle, Vidhisha Chadda and Ahmad R.</p><p>With the challenge and support from Fred Baker; guidance and feedback from Ben Gilpin, Georgia Smith and Jessica Harding; and support throughout the internship from Louise Keevill.</p></div></section>
  <div className="hex-section-inner rover-links"><Link href="/projects">Explore my projects ↗</Link><Link href="/contact">Let’s connect ↗</Link></div>
 </article>;
}
