"use client";
import { useRef } from "react";
import { Crown } from "lucide-react";
import Link from "next/link";
import { useScrollReveals } from "./use-scroll-reveals";
import { InlineArrow } from "@/components/inline-arrow";
export function MarshGazersOverview() {
  const study = useRef<HTMLElement>(null);
  useScrollReveals(study);
  return <article className="marsh-overview project-story-study" ref={study}>
    <header className="marsh-logo-hero"><h1 className="sr-only">MarshGazers</h1><img src="/media/marshgazers/logo.png" alt="MarshGazers telescope logo" width={2048} height={962} loading="eager" /><p className="eyebrow page-enter">UCL East / Student-led rover team</p><p className="marsh-tagline page-enter">From Marshgate to a Mars mission.</p><a className="page-enter" href="#marsh-story">Meet the team ↓</a></header>
    <section id="marsh-story" className="hex-section"><div className="hex-section-inner marsh-story-grid"><div data-reveal><p className="eyebrow">01 / Who we are</p><h2>A dream to see<br />what’s out there.</h2><p className="hex-section-lead">MarshGazers began with a shared curiosity about what lies beyond our everyday surroundings, and a dream of building something that could explore it. Based at UCL East, we wanted to turn that curiosity into a rover and take our learning further than the classroom.</p><p className="hex-section-lead">Our name brings together Marshgate, the home of our Robotics and Artificial Intelligence programme, and the idea of gazing towards new horizons. It reflects our ambition to help make UCL East a place known for innovation.</p></div><figure className="marsh-story-photo" data-reveal><img src="/media/marshgazers/team-ucl.webp" alt="The four MarshGazers co-founders with their rover beside the UCL sign" width={1600} height={1068} loading="lazy" /></figure></div></section>
    <section className="hex-section hex-section-tinted"><div className="hex-section-inner marsh-story-grid marsh-founders-grid"><div data-reveal><p className="eyebrow">The genesis of the team</p><h2>One idea.<br />Four co-founders.</h2><p className="hex-section-lead">Fahd Adel had the original dream and took the first step, bringing together a preliminary team. Sean, Dami and I joined him as co-founders, helping turn his vision into MarshGazers and laying the foundations for our first rover competition.</p><p className="hex-section-lead">Fahd captained our 2024–25 Basic Stream entry. For the 2025–26 Advanced Stream, Sean became captain, with Dami and me as vice captains, bringing experienced members and new recruits into the next mission.</p></div><figure className="marsh-story-photo" data-reveal><img src="/media/marshgazers/founders.webp" alt="MarshGazers co-founders, from left to right: Yusuf, Sean, Dami and Fahd" width={1600} height={1066} loading="lazy" /><figcaption>From left: Yusuf, Sean, Dami and Fahd.</figcaption></figure></div></section>
    <section className="hex-section hex-section-espresso"><div className="hex-section-inner" data-reveal><p className="eyebrow">02 / A national stage</p><h2>Put our learning<br />to the test.</h2><p className="hex-section-lead">The Olympus Rover Trials challenge university teams to design, build and operate a rover for an analogue Mars mission. Organised by UKSEDS with support from Airbus and RAL Space, the competition brings planetary exploration into a practical engineering challenge.</p><p className="hex-section-lead">For us, it was a chance to apply our Robotics and Artificial Intelligence degree on a national stage: connecting mechanical design, embedded electronics and software while learning to communicate, make decisions and deliver as a team.</p><p className="hex-section-lead">Our first rover explored through a camera. The next aimed to collect regolith samples, engaging with the challenge of understanding and using resources already on Mars.</p><div className="marsh-partners" aria-label="Competition organisations"><img src="/media/partners/ukseds.png" alt="UKSEDS" width={1989} height={528} loading="lazy" /><img src="/media/partners/airbus.png" alt="Airbus" width={2048} height={758} loading="lazy" /><img src="/media/partners/ral-space.png" alt="RAL Space" width={476} height={148} loading="lazy" /></div></div></section>
    <section className="hex-section" aria-labelledby="marsh-missions"><div className="hex-section-inner"><div data-reveal><p className="eyebrow">03 / Two seasons, two missions</p><h2 id="marsh-missions">The rovers we built.</h2></div><div className="marsh-competition-grid">
      <Link className="marsh-competition-card" href="/projects/olympus-basic" data-reveal><img src="/media/olympus-basic/rover-ral-space.webp" alt="Tracked Basic Stream rover on the vibration bed at RAL Space" width={1600} height={1066} loading="lazy" /><div><p className="eyebrow">2024–25 / UKSEDS × RAL Space</p><h3>Olympus Basic</h3><p>Teleoperated reconnaissance. Tracks, a two-joint camera arm and QR image collection.</p><span>Explore the first season <InlineArrow /></span></div></Link>
      <Link className="marsh-competition-card marsh-competition-advanced" href="/projects/olympus-advanced" data-reveal style={{transitionDelay:"180ms"}}><img src="/media/olympus-advanced/rover-sand.webp" alt="Advanced Stream rover close up on the sand course" width={1600} height={1066} loading="lazy" /><div><p className="eyebrow">2025–26 / UKSEDS × Airbus</p><h3>Olympus Advanced</h3><p>Planetary sampling. Four-wheel mobility, a RASSOR-inspired drum and a design towards autonomy.</p><span>Explore the next mission <InlineArrow /></span></div></Link>
    </div></div></section>
    <section className="hex-section hex-section-tinted" aria-labelledby="marsh-awards"><div className="hex-section-inner"><div data-reveal><p className="eyebrow">04 / Recognition along the way</p><h2 id="marsh-awards">What we brought home.</h2></div><div className="marsh-awards"><div className="hex-story-card" data-reveal><p className="eyebrow">Basic Stream / 2024–25</p><Crown className="award-crown award-silver" aria-label="Silver crown"/><h3>2nd place nationally</h3><p>Best Automation Award<br />Best Outreach Award</p></div><div className="hex-story-card" data-reveal style={{transitionDelay:"180ms"}}><p className="eyebrow">Advanced Stream / 2025–26</p><Crown className="award-crown award-bronze" aria-label="Bronze crown"/><h3>3rd place nationally</h3><p>Best Critical Design Review.</p></div></div></div></section>
  </article>;
}
