"use client";
import { useRef } from "react";
import { Crown } from "lucide-react";
import Link from "next/link";
import { useScrollReveals } from "./use-scroimport { InlineArrow } from "@/components/inline-arrow";
ll-reveals";
export function MarshGazersOverview() {
  const study = useRef<HTMLElement>(null);
  useScrollReveals(study);
  return <article className="marsh-overview project-story-study" ref={study}>
    <header className="marsh-logo-hero"><h1 className="sr-only">MarshGazers</h1><img src="/media/marshgazers/logo.png" alt="MarshGazers telescope logo" width={2048} height={962} loading="eager" /><p className="eyebrow">UCL East / Student-led rover team</p><p className="marsh-tagline">From Marshgate to a Mars mission.</p><a href="#marsh-story">Meet the team ↓</a></header>
    <section id="marsh-story" className="hex-section"><div className="hex-section-inner hex-story-grid"><div data-reveal><p className="eyebrow">01 / Who we are</p><h2>Nine students.<br />One shared horizon.</h2><p className="hex-section-lead">MarshGazers is a student-led rover team based at UCL East, home of the Robotics and Artificial Intelligence programme. Our name comes from Marshgate, the building where our course began, and our ambition to help make UCL East a place known for innovation.</p></div><div className="hex-story-card" data-reveal style={{transitionDelay:"180ms"}}><h3>How we came together.</h3><p>Fahd Adel established the team with co-creators Sean, Yusuf and Dami. Our first competition season brought nine students together to turn the skills we were learning into a rover we could build, operate and take to a national competition.</p><p>Fahd captained the 2024–25 Basic Stream entry. Sean became captain for the 2025–26 Advanced Stream, with Dami and Yusuf as vice captains, bringing experienced members and new recruits into the next mission.</p></div></div></section>
    <section className="hex-section hex-section-espresso"><div className="hex-section-inner" data-reveal><p className="eyebrow">02 / More than a rover</p><h2>Learn together.<br />Build something that works.</h2><p className="hex-section-lead">The Olympus Rover Trials gave us an analogue Mars mission with real engineering constraints. It was also a chance to practise the less visible parts of engineering: communicating across subteams, making decisions together and managing a project from first concept to field preparation.</p><p className="hex-section-lead">Our first rover explored through a camera. The next aimed to collect regolith samples, engaging with the challenge of understanding and using resources already on Mars. Both missions connect mechanical design, embedded electronics and software around one purpose.</p></div></section>
    <section className="hex-section" aria-labelledby="marsh-missions"><div className="hex-section-inner"><div data-reveal><p className="eyebrow">03 / Two seasons, two missions</p><h2 id="marsh-missions">The rovers we built.</h2></div><div className="marsh-competition-grid">
      <Link className="marsh-competition-card" href="/projects/olympus-basic" data-reveal><img src="/media/olympus-basic/rover-ral-space.webp" alt="Tracked Basic Stream rover on the vibration bed at RAL Space" width={1600} height={1066} loading="lazy" /><div><p className="eyebrow">2024–25 / UKSEDS × RAL Space</p><h3>Olympus Basic</h3><p>Teleoperated reconnaissance. Tracks, a two-joint camera arm and QR image collection.</p><span>Explore the first season <InlineArrow /></span></div></Link>
      <Link className="marsh-competition-card marsh-competition-advanced" href="/projects/olympus-advanced" data-reveal style={{transitionDelay:"180ms"}}><img src="/media/olympus-advanced/rover-sand.webp" alt="Advanced Stream rover close up on the sand course" width={1600} height={1066} loading="lazy" /><div><p className="eyebrow">2025–26 / UKSEDS × Airbus</p><h3>Olympus Advanced</h3><p>Planetary sampling. Four-wheel mobility, a RASSOR-inspired drum and a design towards autonomy.</p><span>Explore the next mission <InlineArrow /></span></div></Link>
    </div></div></section>
    <section className="hex-section hex-section-tinted" aria-labelledby="marsh-awards"><div className="hex-section-inner"><div data-reveal><p className="eyebrow">04 / Recognition along the way</p><h2 id="marsh-awards">What we brought home.</h2></div><div className="marsh-awards"><div className="hex-story-card" data-reveal><p className="eyebrow">Basic Stream / 2024–25</p><Crown className="award-crown award-silver" aria-label="Silver crown"/><h3>2nd place nationally</h3><p>Best Automation Award<br />Best Outreach Award</p></div><div className="hex-story-card" data-reveal style={{transitionDelay:"180ms"}}><p className="eyebrow">Advanced Stream / 2025–26</p><Crown className="award-crown award-bronze" aria-label="Bronze crown"/><h3>3rd place nationally</h3><p>Best Critical Design Review: 89/100.<br/>Preliminary Design Report: 73/100, Grade A.</p></div></div></div></section>
  </article>;
}
