"use client";
import {useRef} from "react";
import Link from "next/link";
import {BuildCarousel,type BuildFrame} from "./build-carousel";
import {useScrollReveals} from "./use-scroll-reveals";
import type {Project} from "@/conimport { InlineArrow } from "@/components/inline-arrow";
tent/types";
const stages=[
 {file:"early-concept.webp",title:"Start with the climb",context:"Our initial concept used two grippers connected by a lead-screw mechanism. Alternating which gripper held the trunk would let the other section advance. I led the design and mechatronics work as the team explored that sequence."},
 {file:"climbing-sequence.webp",title:"Think through each step",context:"These sketches show the intended alternating grip and climb sequence. They describe the proposed motion, rather than proof of a completed climb, canopy-sensor deployment and return."},
 {file:"gripper-sketch.webp",title:"The first grip",context:"The early concept used rigid fingers and geared actuation. We explored how a servo-driven gripper could hold the trunk while the other section moved."},
 {file:"rigid-gripper-drawing.webp",title:"Make the geometry buildable",context:"The dimensioned drawing records the earlier rigid gripper. CAD let us work through the arrangement before manufacture, while later prototypes exposed the importance of mass and grip behaviour."},
 {file:"rigid-prototype.webp",title:"Learn from the prototype",context:"The manufactured rigid gripper was an earlier iteration. We rejected acrylic and plywood finger concepts because of their mass and behaviour, and moved towards a lighter compliant approach."},
 {file:"compliant-prototype.webp",title:"Let the fingers adapt",context:"The later compliant PLA gripper used strings and a servo to close lightweight fingers around the trunk. This prototype helped the team explore a grip that could adapt to the surface rather than rely only on rigid geometry."},
 {file:"lower-body-drawing.webp",title:"Support the moving body",context:"The lower-body drawing shows the compliant gripper and motor arrangement. I led rapid prototyping and troubleshooting, including guide-rod support, centre-of-mass changes and gripper actuation."},
 {file:"upper-body-drawing.webp",title:"Arrange the upper section",context:"The upper-body views record the compliant fingers and ultrasonic sensor placement. The two sections had to work together through the intended alternating grip sequence."},
 {file:"assembly-drawing.webp",title:"Bring the mechanism together",context:"The later assembly drawing combines the two compliant grippers, guide rods and climbing mechanism. It records the team's developed design following the earlier rigid-gripper iteration."},
 {file:"assembled-prototype.webp",title:"The final demonstration",context:"The assembled prototype demonstrated that the compliant gripper could adapt to and hold the trunk. Ascent was slower than intended and the overall demonstration was a partial success; a complete climb, sensor deployment and return is not claimed."},
];
export function TreeClimbingStudy({project}:{project:Project}) {
 const study=useRef<HTMLElement>(null);useScrollReveals(study);
 const hero={src:"/media/tree-climbing-robot/compliant-hero.webp",alt:"Close-up of the compliant string-actuated gripper prototype and its electronics",width:2000,height:1701};
 const frames:BuildFrame[]=stages.flatMap(stage=>{const media=project.media.find(m=>m.src.endsWith('/'+stage.file));return media?[{media,title:stage.title,caption:media.caption||stage.title,context:stage.context}]:[];});
 return <article className="tree-study project-story-study" ref={study}>
  <header className="hex-hero"><div className="hex-intro"><p className="eyebrow hex-enter">UCL / First Year, Final Term Challenge</p><h1><span className="hex-title">Tree Climbing Robot</span></h1><p className="hex-summary hex-enter">Climb a tree. Place a canopy sensor. Find a way back down.</p></div>{hero&&<figure className="hex-hero-image"><img src={hero.src} alt={hero.alt} width={hero.width} height={hero.height} loading="eager"/></figure>}</header>
  <section className="hex-section tree-question"><div className="hex-section-inner" data-reveal><p className="eyebrow">01 / The challenge</p><h2>Before the next step,<br/>earn the next grip.</h2><p className="hex-section-lead">Our first-year final-term project asked us to build a robot that could climb a tree, deploy a sensor in the canopy and return to the ground. Between April and June 2024, the team worked towards a final showdown. Every upward movement depended on the same question: could the robot hold on while part of it moved?</p></div></section>
  <section className="hex-section"><div className="hex-section-inner hex-story-grid"><div className="hex-story-card" data-reveal><h2>Two grips.<br/>One climbing cycle.</h2><p>We developed alternating upper and lower grippers linked by a lead-screw mechanism. One section would hold the trunk while the other advanced, then the grip would transfer for the next movement.</p></div><div className="hex-story-card" data-reveal style={{transitionDelay:"180ms"}}><h3>My role in the build.</h3><p>I led the design and mechatronics work, taking the mechanism through rapid prototyping and troubleshooting. Guide-rod support, centre of mass and gripper actuation all became part of the iteration as we worked towards a system we could demonstrate.</p></div></div></section>
  <section className="hex-section hex-section-espresso"><div className="hex-section-inner"><div data-reveal><p className="eyebrow">02 / Let the prototype teach us</p><h2>A lighter way to hold on.</h2></div><div className="hex-engineering-grid"><div className="hex-story-card" data-reveal><h3>Begin with rigid fingers.</h3><p>Our earlier concepts used rigid fingers and servo actuation. Acrylic and plywood options added mass and did not give us the behaviour we wanted.</p></div><div className="hex-story-card" data-reveal style={{transitionDelay:"180ms"}}><h3>Move towards compliance.</h3><p>We developed lighter compliant PLA fingers, actuated by strings. Their flexibility allowed the later gripper to adapt to the trunk and hold it in a working demonstration.</p></div><div className="hex-story-card" data-reveal style={{transitionDelay:"360ms"}}><h3>Keep the whole system in view.</h3><p>A workable gripper was only one part of the climb. The body support, balance and lead-screw motion also had to work together, and ascent remained slower than we intended.</p></div></div></div></section>
  <section className="hex-section hex-build-section"><div className="hex-section-inner hex-build-introduction" data-reveal><p className="eyebrow">03 / Concept to compliant prototype</p><h2>The build, frame by frame.</h2><p className="hex-section-lead">Follow the sketches, drawings and physical iterations. Select an image for the closer story.</p></div><BuildCarousel frames={frames} label="Tree Climbing Robot build story"/></section>
  <section className="hex-section hex-section-tinted"><div className="hex-section-inner hex-story-grid"><div className="hex-story-card" data-reveal><p className="eyebrow">04 / What we achieved</p><h2>A grip that worked.<br/>A climb to improve.</h2><p>The compliant gripper adapted to and held the trunk in a working demonstration. The overall result was a partial success: ascent was slower than planned, and we did not demonstrate the complete climb, sensor deployment and return.</p></div><div className="hex-story-card" data-reveal style={{transitionDelay:"180ms"}}><h3>The lesson I took forward.</h3><p>The project showed me how quickly a promising mechanism becomes a system problem. Making a finger lighter changed the load on the climbing mechanism; changing the body support affected the grip. Iterating with the physical prototype helped connect those decisions.</p></div></div></section><div className="hex-section-inner rover-links"><Link href="/projects">Explore all projects <InlineArrow /></Link></div>
 </article>;
}
